variable "env" {
  description = "Environment name (dev / staging / prod)"
  type        = string
}

variable "project" {
  description = "Project name — used as a prefix for all resource names"
  type        = string
}

# ── Network ───────────────────────────────────────────────────────────────────

variable "vpc_id" {
  description = "VPC ID — from module.vpc.vpc_id"
  type        = string
}

variable "public_subnet_ids" {
  description = "List of public subnet IDs — ALB must be in public subnets to receive internet traffic"
  type        = list(string)
}

variable "alb_sg_id" {
  description = "Security group ID for the ALB — from module.security_groups.alb_sg_id"
  type        = string
}

# ── Target group ──────────────────────────────────────────────────────────────

variable "health_check_path" {
  description = "Health check endpoint — must match your Flask /api/health route"
  type        = string
  default     = "/api/health"
}

# ── CloudFront secret ─────────────────────────────────────────────────────────
# Generated by secrets module — passed here to set as ALB listener rule condition.
# ALB rejects any request that does not include this header value.
# This locks the ALB to CloudFront traffic only — direct ALB access returns 404.

variable "cloudfront_secret" {
  description = "CloudFront origin verification header value — from module.secrets.cloudfront_secret_value"
  type        = string
  sensitive   = true
}